"""IR → PostgreSQL DDL.

테이블을 모두 만든 뒤 FK를 ALTER TABLE로 붙인다 — 테이블 생성 순서를 신경 쓸 필요가
없고, 순환 참조도 그대로 표현된다. 한글 논리명과 설명은 COMMENT로 남겨 pgxnl이
입력 메타데이터로 읽을 수 있게 한다(plan.md §개요).
"""
from __future__ import annotations

from nlxpg.ir import Entity, SchemaIR
from nlxpg.modeling.naming import surrogate_key_name


def _q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _ident(s: str) -> str:
    return s[:63]


def _comment(logical: str, description: str) -> str:
    return f"{logical}: {description}" if description and description != logical else logical


def _fk_columns(ir: SchemaIR, table: str) -> set[str]:
    return {
        c for r in ir.relationships if r.foreign_key and r.foreign_key.table == table
        for c in r.foreign_key.columns
    }


def _is_identity(e: Entity, fk_cols: set[str]) -> bool:
    if len(e.primary_key) != 1:
        return False
    col = e.attribute(e.primary_key[0])
    return (
        col is not None and col.physical_name == surrogate_key_name(e.physical_name)
        and col.data_type in ("bigint", "integer") and col.physical_name not in fk_cols
    )


def to_ddl(ir: SchemaIR, *, schema: str | None = None) -> str:
    prefix = f"{schema}." if schema else ""
    out: list[str] = ["-- nlxpg generated DDL", f"-- schema_version {ir.schema_version}", ""]
    if schema:
        out += [f"CREATE SCHEMA IF NOT EXISTS {schema};", ""]

    for e in ir.entities:
        fk_cols = _fk_columns(ir, e.physical_name)
        identity = _is_identity(e, fk_cols)
        lines: list[str] = []
        for a in e.attributes:
            col = f"    {a.physical_name} {a.data_type}"
            if identity and a.physical_name == e.primary_key[0]:
                col += " GENERATED BY DEFAULT AS IDENTITY"
            if not a.nullable:
                col += " NOT NULL"
            lines.append(col)
        if e.primary_key:
            lines.append(f"    CONSTRAINT {_ident(e.physical_name + '_pk')} PRIMARY KEY ({', '.join(e.primary_key)})")
        for a in e.attributes:
            if a.is_unique and not a.is_primary_key:
                uk = _ident(f"{e.physical_name}_{a.physical_name}_uk")
                lines.append(f"    CONSTRAINT {uk} UNIQUE ({a.physical_name})")
        out.append(f"CREATE TABLE {prefix}{e.physical_name} (")
        out.append(",\n".join(lines))
        out.append(");")
        out.append(f"COMMENT ON TABLE {prefix}{e.physical_name} IS {_q(_comment(e.logical_name, e.description))};")
        for a in e.attributes:
            out.append(
                f"COMMENT ON COLUMN {prefix}{e.physical_name}.{a.physical_name} "
                f"IS {_q(_comment(a.logical_name, a.description))};"
            )
        out.append("")

    names: set[str] = set()
    for r in ir.relationships:
        fk = r.foreign_key
        if fk is None:
            continue
        parent = ir.entity(r.from_entity)
        ref_cols = fk.ref_columns or (parent.primary_key if parent else [])
        cname = f"{fk.table}_{r.from_entity}_fk"[:60]
        i = 2
        base = cname
        while cname in names:
            cname = f"{base[:57]}_{i}"
            i += 1
        names.add(cname)
        out.append(
            f"ALTER TABLE {prefix}{fk.table} ADD CONSTRAINT {cname} "
            f"FOREIGN KEY ({', '.join(fk.columns)}) "
            f"REFERENCES {prefix}{r.from_entity} ({', '.join(ref_cols)});"
        )
    return "\n".join(out).rstrip() + "\n"
