from nlxpg.generate import to_ddl, to_markdown, to_mermaid
from nlxpg.modeling import design_schema
from nlxpg.validate import lint_schema


def test_ddl(order_ir):
    ddl = to_ddl(design_schema(order_ir))
    assert "CREATE TABLE customer (" in ddl
    assert "customer_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL" in ddl
    assert "CONSTRAINT product_product_code_uk UNIQUE (product_code)" in ddl
    assert "COMMENT ON TABLE customer IS '거래처';" in ddl
    assert "FOREIGN KEY (customer_id) REFERENCES customer (customer_id)" in ddl
    # 연결 테이블의 PK 컬럼은 FK이므로 IDENTITY가 아니다
    assert "product_id bigint NOT NULL" in ddl


def test_erd_and_markdown(order_ir):
    ir = design_schema(order_ir)
    erd = to_mermaid(ir)
    assert erd.startswith("erDiagram")
    assert "varchar_100 customer_name" in erd
    assert "customer ||--o{ order_" in erd
    assert "## 거래처 (`customer`)" in to_markdown(ir)


def test_lint_clean(order_ir):
    errors = [i for i in lint_schema(design_schema(order_ir)) if i.level == "error"]
    assert errors == []
